language: python
matrix:
  include:
    - name: "Python 3.5 on Xenial Linux 16.04"
      python:
        - "3.5"
      dist: xenial
    - name: "Python 3.6 on Xenial Linux 16.04"
      python:
        - "3.6"
      dist: xenial
    - name: "Python 3.7 on Xenial Linux 16.04"
      python:
        - "3.7"
      dist: xenial
    - name: "Python 3.5 on Bionic Linux 18.04"
      python:
        - "3.5"
      dist: bionic
    - name: "Python 3.6 on Bionic Linux 18.04"
      python:
        - "3.6"
      dist: bionic
    - name: "Python 3.7 on Bionic Linux 18.04"
      python:
        - "3.7"
      dist: bionic

before_install:
  # Install Anaconda
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
    wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - conda activate test-environment

install:
  - pip install pip -U
  - pip install tensorflow==1.15.2
  - pip install -e .

script:
  - pip install pytest pytest-cov
  - pytest --cov=baconian ./baconian/examples/ ./baconian/test/

notifications:
  email: false

after_success:
  - codecov